# Machine Learning : Numpy Tutorial

In [2]:
import numpy as np

## 1.Creating array in numpy 

In [16]:
#numpy array one dimentional
arr1=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
## numpy array 2 dimentional (like a matrix)
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#numpy array three dimentional
arr3=np.array([
    [[1,2,3],[1,2,3],[1,5,4]],
    [[1,2,3],[3,5,6],[6,7,8]],
    [[4,4,5],[2,4,5],[5,6,7]]
])
arr3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 5, 4]],

       [[1, 2, 3],
        [3, 5, 6],
        [6, 7, 8]],

       [[4, 4, 5],
        [2, 4, 5],
        [5, 6, 7]]])

## 2. Properties of Numpy Array

In [21]:
# Shape of array 
arr2.shape 

(3, 3)

In [24]:
arr3.shape

(3, 3, 3)

In [27]:
# total elements of array or size of an array
arr2.size

9

In [29]:
arr3.size

27

In [30]:
arr1.size

7

In [31]:
#checking the dimentions of array
arr2.ndim

2

In [32]:
arr1.ndim

1

In [33]:
arr3.ndim

3

In [35]:
# Checking the datatype of an array
arr1.dtype

dtype('int64')

In [36]:
arr3.dtype

dtype('int64')

In [38]:
arr2.dtype

dtype('int64')

## Special Functions of Numpy Arrray

In [40]:
type(arr2)

numpy.ndarray

In [41]:
type(arr3)

numpy.ndarray

In [42]:
type(arr)

numpy.ndarray

In [47]:
#ones() and zeros() function of array
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
arr4=np.zeros((3,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
# arange() function  as same as loop range()
arr5 = np.arange(1,28).reshape(3,3,3)
print(arr5,'\n',type(arr5),'\n',arr5.ndim,'\n',arr5.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 
 <class 'numpy.ndarray'> 
 3 
 int64


In [77]:
#linspace() function 
#reshape() function (dimention,row,columns)
arr6=arr5.reshape(9,3)
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [78]:
arr6.ndim

2

In [81]:
#converting the multidimentional aarray to one dim array using ravel() 
arr7=arr5.ravel()
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [82]:
arr7.ndim

1

In [87]:
#converting the multidimentional aarray to one dim array using flatten()
arr8=arr5.flatten()
arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [86]:
arr8.ndim

1

In [90]:
#transpose the matrix (change row into column && column into row) using transpose()
arr_tr=arr5.transpose()
print('Untranspose array : \n',arr5,' \n Transposed: \n',arr_tr)

Untranspose array : 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]  
 Transposed: 
 [[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]


##  Performing Arithmatic  operations on Numpy array or data

In [97]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(10,19).reshape(3,3)
print(arr1,'\n \n',arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [98]:
# addion of arrays 
arr1+arr2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [105]:
# addion of arrays 
np.add(arr1,arr2)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [104]:
# addion of arrays 
arr2-arr1

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [106]:
np.subtract(arr2,arr1)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [113]:
# Add by (+) or np.add()
# Subtraction using (-) and np.subtract()
# Multipliction by (*) and np.multiply()

print('(*): \n',arr1*arr2)
print('np.multiply():\n',np.multiply(arr1,arr2))

# Divide by (/) and np.divide()
print('(/):\n',arr1/arr2)
print('np.divide():\n',np.divide(arr1,arr2))

(*): 
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
np.multiply():
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
(/):
 [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
np.divide():
 [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [117]:
# Warnning: Now * is the multiplication of the matrix not a product of matrix 
# Product of matrix by (@) and np.dot()
print(arr1@arr2)
print(np.dot(arr1,arr2))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [118]:
# Cross of the matrix by the np.cross()
np.cross(arr1,arr2)

array([[-9, 18, -9],
       [-9, 18, -9],
       [-9, 18, -9]])

In [130]:
# Max Value of the matrix
print(arr1.max())
# getting the index of max number
print(arr1.argmax())
# getting the max values in the row
print(arr1.max(axis=1))
#getting the min values index in row
print(arr1.argmax(axis=1))
# getting the max values in the column 
print(arr1.max(axis=0))
#getting the min values index in column
print(arr1.argmax(axis=0))

9
8
[3 6 9]
[2 2 2]
[7 8 9]
[2 2 2]


In [131]:
# Getting min value of the matrix
print(arr2.min())
#getting the index of the min value 
print(arr2.argmin())
# getting the max values in the row
print(arr2.min(axis=1))
#getting the min values index in row
print(arr2.argmin(axis=1))
# getting the max values in the column
print(arr2.min(axis=0))
#getting the min values index in column
print(arr2.argmin(axis=0))

10
0
[10 13 16]
[0 0 0]
[10 11 12]
[0 0 0]


In [134]:
# Self Addition of matrix
print(np.sum(arr2))
# Self Addition of matrix by row
print(np.sum(arr2,axis=1))
# Self Addition of matrix by column
print(np.sum(arr2,axis=0))

126
[33 42 51]
[39 42 45]


In [136]:
# Mean of the Matrix
print(np.mean(arr2))
# Mean of the Matrix by Row
print(np.mean(arr2 , axis = 1))
# Mean of the Matrix by Column
print(np.mean(arr2 , axis = 0))

14.0
[11. 14. 17.]
[13. 14. 15.]


In [138]:
# square root of the matrix by each element
np.sqrt(arr2)

array([[3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069]])

In [139]:
# Standerd Division of the matrix
np.std(arr2)

2.581988897471611

In [141]:
#exponent of the matrix each element
np.exp(arr2)

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]])

In [143]:
#log of matrix by each element 
print(np.log(arr2))
# log10 of matrix
print(np.log10(arr2))

[[2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502 ]
 [2.77258872 2.83321334 2.89037176]]
[[1.         1.04139269 1.07918125]
 [1.11394335 1.14612804 1.17609126]
 [1.20411998 1.23044892 1.25527251]]


## Array Slicing of numpy

In [154]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [163]:
#getting a row by index
arr2[2,:]

array([16, 17, 18])

In [157]:
arr2[2].ndim

1

In [160]:
#getting a column by index
arr2[:,2]

array([12, 15, 18])

In [161]:
arr2[:,2].ndim

1

In [156]:
# getting a value on the specific index
arr2[1,1]

14

In [162]:
# getting a value on the specific index
arr2[1,1].ndim

0

In [166]:
#getting data from matrix 
arr2[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [168]:
#getting full matrix by [:] or [::] 
arr2[:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [170]:
arr2[::]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [185]:
# itemsize of an array 
arr2.itemsize

8

In [187]:
# array Concatination and split
np.concatenate((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [190]:
# concatenate by row
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [192]:
# Concatenation by column
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [195]:
#vertical Concatenate the matrix
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [202]:
# horizontally concatenate the array
hs=np.hstack((arr1,arr2))
hs

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [211]:
#spliting arrays 
np.split(hs,3)

[array([[ 1,  2,  3, 10, 11, 12]]),
 array([[ 4,  5,  6, 13, 14, 15]]),
 array([[ 7,  8,  9, 16, 17, 18]])]

In [217]:
#row wise spliting
print(np.split(hs,3,axis=0))

[array([[ 1,  2,  3, 10, 11, 12]]), array([[ 4,  5,  6, 13, 14, 15]]), array([[ 7,  8,  9, 16, 17, 18]])]


In [218]:
#column wise spliting
print(np.split(hs,2,axis=1))

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


## Trigonometrix in data

In [232]:
# np.sin(angle), np.cos(angle), np.tan(angle)
print(np.sin(130))
print(np.cos(130))
print(np.tan(130))
print(np.sin(30))
print(np.sin(90))

-0.9301059501867618
-0.3672913304546965
2.5323384274693232
-0.9880316240928618
0.8939966636005579


## Random Sampling with Random Package

In [233]:
import random

In [234]:
# Creating an array
np.random.random([3,3])

array([[0.14667906, 0.65346219, 0.15065116],
       [0.77092496, 0.88438183, 0.46468011],
       [0.97662062, 0.46782694, 0.01210251]])

In [236]:
np.random.randint(1,4,(4,4))

array([[1, 3, 2, 1],
       [2, 3, 3, 1],
       [1, 3, 2, 3],
       [3, 2, 2, 1]])

In [239]:
np.random.seed(10)
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [240]:
np.random.rand(3,3)

array([[0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335]])

In [241]:
np.random.randn(3,3)

array([[ 0.00429143, -0.17460021,  0.43302619],
       [ 1.20303737, -0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761, -1.13660221]])

In [243]:
np.random.choice(3)

1

## String Methods via Numpy

In [244]:
# np.char.add()
# np.char.uppercase()
# np.char.lowercase()
# np.char.split()